[env:esp32doit-devkit-v1]
platform  = espressif32
board     = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200

lib_deps =
    ESP32 BLE Arduino
    IRremote/IRremote @ ^4.4.0
    kosme/arduinoFFT @ ^2.0.2

build_flags =
    -Wno-pragmas
    -DSEND_PWM_BY_TIMER
